services:
  web:
    container_name: web
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - public-data:/api/public
      - tmp-data:/api/tmp
    ports:
      - "80:80"
    depends_on:
      - front
      - api
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    volumes:
      - ./backend:/api
      - public-data:/api/public
      - tmp-data:/api/tmp
      - log-data:/api/log
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    container_name: db
    image: mysql:8.0
    platform: linux/amd64
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
  front:
    container_name: front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/front
    ports:
      - "8000:3000"
    tty: true
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true

volumes:
  db-volume:
  public-data:
  tmp-data:
  log-data:
